steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "  GCP_PROJECT: ${_GCP_PROJECT}" >> app.yaml
    echo "  SLACK_TOKEN: ${_SLACK_TOKEN}" >> app.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy',
   '--no-promote',
   '--stop-previous-version',
   '--project', '${_GCP_PROJECT}',
   '--version', '$SHORT_SHA',
   '--quiet']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'services','set-traffic',
   '--project', '${_GCP_PROJECT}',
   '--splits', '$SHORT_SHA=1',
   '--quiet']
