runtime: nodejs14

handlers:

# Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: frontend/dist/\1
    upload: frontend/dist/(.*\..+)$

# Catch all handler to index.html
  - url: /
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

# Other configurations should go above env_variables section.
env_variables:
  NODE_ENV: production
