runtime: nodejs14

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static
    static_dir: public

# Serve all static files with url ending with a file extension
  - url: /vuejs-app/(.*\..+)$
    static_files: frontend/dist/\1
    upload: frontend/dist/(.*\..+)$
# Catch all handler to index.html
  - url: /vuejs-app/.*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

# Other configurations should go above env_variables section.
env_variables:
  NODE_ENV: production
