runtime: nodejs14

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static
    static_dir: public

  - url: /vuejs-app
    static_dir: frontend/dist

# Other configurations should go above env_variables section.
env_variables:
  NODE_ENV: production
